[package]
name = "click_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.13.1"

[dependencies.windows]
version = "0.43.0"
features = [
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
]
